### ISSUE TITLE
Feature Request: Timed Snapshots

### ISSUE THREAD

**Issue by alolalo** [larryhudson/eleventy-plugin-prince-pdf#1]
First of all, fantastic idea to make a share code visually with a simple PDF. I believe it's well worth the notion of how most code reviews, personal or professional, **never happen visually**. Even GitHub just "sees" your work as a "checkbox square"

I hope to change that notion, and that you can have a directory of "visual change logs" that accompany such achievements, and help developers just pull up a PDF to show the IRL differences that we interface with, not the DIFF-messages you pull in.

Ideally it should work as a true-false configuration that, just like an ordinary camera, takes snapshots of your url's every X minutes | hours | days | weeks | months | years even, and put them into a folder named accordingly. 

A **catablog** of work done on auto-pilot, so you can continue **not using this plugin** to use it optimally. Right? It's meant to offload the work for you and automating the "hard parts" of work; Communication 

It would greatly help **re-use** my actual work, in combination with all the pushing and pulling repositories, that you can put them side by side easily, isolated, and have a chat with someone on the visual plane of change that **actually happened**.

**Comment by larryhudson** [comment]
Hi there, I think this falls outside the scope of this project, as this is an Eleventy extension that generates PDFs of certain URLs inside your Eleventy site after the HTML is rendered.

But this is an interesting idea. For your scenario, I think saving URL snapshot images might be a better solution than saving PDFs. PDFs are more suited for print documents (eg. A4 document size). So if you made PDFs of all your webpages, the pages would be split up into A4 pages, which isn't ideal for visual reviews.

If you want to code something yourself, you could write a Node script loops through an array of webpages and uses Google's [Puppeteer](https://developers.google.com/web/tools/puppeteer/) to take screenshot images, and then upload them to a [S3 storage bucket](https://www.mydatahack.com/uploading-and-downloading-files-in-s3-with-node-js/). You could use a [cron job](https://www.hostinger.com/tutorials/cron-job) to execute the script every week, or every month etc.

**Comment by larryhudson** [comment]
Hey, not sure if you’ll see this but I just came across shot-scraper, which sounds like a solution to what you were asking for:
https://github.com/simonw/shot-scraper-template
